* 二元配置分散分析って何？【交互作用が分かります】

分散分析を用いると、注目している要素が結果に効果を与えているかを知ることが出来ます。

- [[https://sigma-eye.com/2019/04/08/what-bunsanbunseki/][分散分析とは何ですか？【分散で要因を特定します】]]

以前[[https://sigma-eye.com/2019/04/10/ichigen-bunsanbunseki/][一元配置分散分析]]と二元配置分散分析に大別されると紹介していますが、この一元と二元は響きでは大差無いように思われますが、得られる情報量が大きく異なります。

今回は2元配置分散分析を紹介します。

原理だけは押さえて、実用はエクセルで行いましょう。

*統計学がうまく使えなかった人はコチラ*⇒[[https://note.com/komichi_kumano/n/n7684d2ef6bd9][統計学を活かす
解析しやすい数値化のノウハウ]]

** 二元配置分散分析の計算方法
 
今回の二元配置分散分析を始めとした、分散分析の手法は以下の書籍を参考にしています。

多分この記事より面白いです(笑)。ぜひご一読ください。

[[https://hb.afl.rakuten.co.jp/hgc/186822fe.e3f88dc1.186822ff.8dd52a81/yomereba_main_201906081612040284?pc=http%3A%2F%2Fbooks.rakuten.co.jp%2Frb%2F12187159%2F%3Fscid%3Daf_ich_link_urltxt%26m%3Dhttp%3A%2F%2Fm.rakuten.co.jp%2Fev%2Fbook%2F][実験計画と分散分析のはなし改訂版]]

大村平 日科技連出版社 2013年01月

[[https://hb.afl.rakuten.co.jp/hgc/186822fe.e3f88dc1.186822ff.8dd52a81/yomereba_main_201906081612040284?pc=http%3A%2F%2Fbooks.rakuten.co.jp%2Frb%2F12187159%2F%3Fscid%3Daf_ich_link_urltxt%26m%3Dhttp%3A%2F%2Fm.rakuten.co.jp%2Fev%2Fbook%2F][楽天ブックス]]

[[https://www.amazon.co.jp/exec/obidos/asin/481719457X/kumano1235/][Amazon]]

[[https://www.amazon.co.jp/gp/search?keywords=%E5%AE%9F%E9%A8%93%E8%A8%88%E7%94%BB%E3%81%A8%E5%88%86%E6%95%A3%E5%88%86%E6%9E%90%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97%E6%94%B9%E8%A8%82%E7%89%88&__mk_ja_JP=%83J%83%5E%83J%83i&url=node%3D2275256051&tag=kumano1235][Kindle]]

*** 分散分析の計算の流れ


原理的には一元配置分散分析です。

先述した交互作用は、*繰り返しのある二元配置分散*で導くことが出来ます。

『繰り返し』とは、全く同じ条件のN増し実験のことを指します。

一条件に対して、N=1の試験を対象にした分散分析を*繰り返しの無い分散分析*と言います。

さて二元配置分散における各変動を式で表すと、

総分散

$$\sum\sum\sum(x_{ijk}-\overline{\overline{x}})^2$$

群間変動

$$V_i=jk\sum(\overline{x_i}-\overline{\overline{x}})^2$$

$$V_j=ik\sum(\overline{x_j}-\overline{\overline{x}})^2$$

交互作用

$$V_k=k\sum\sum(\overline{x_{ij}}-\overline{\overline{x}})^2-(V_i+V_j)$$

群内変動(誤差)

$$V_g=V-(V_i+V_j+V_k)$$

ハイ、ピンときません

*** 実際に計算してみよう

ある収穫物の収量に対して、肥料と土による効果を分散分析で評価してみましょう。

ここでは要因として肥料と土が挙がります(ちなみに全体の平均値は7になります)。

まず、肥料の効果ですが肥料1の平均値4と肥料2の平均値10がそれぞれのマスを埋めるイメージを持ってください。

この状態の変動([[https://sigma-eye.com/2018/07/09/what-sigma/][偏差平方和]])を計算すると、

$$V_1=4×(4-7)^2+4×(10-7)^2=72$$

となります。

次は土です。

土の偏差平方和は

$$V_2=4×(5-7)^2+4×(9-7)^2=32$$

になります。そして交互作用です。

交互作用=肥料×土の作用ですので、以下のようなマスで考えます。

これで考えると、

$$2×(1-7)^2+2×(1-7)^2+2×(1-7)^2+2×(1-7)^2=112$$

この数字には肥料の変動と土の変動が混ざっていますから、引いてやります。

$$V_k=112-72-32=8$$

最後に誤差ですが、そもそもこの表は

$$総変動=126$$

ですから、そこから今まで算出した変動を総変動から差し引くと

$$誤差=126-(72+32+8)=14$$

これですべての変動が揃いましたが、この後F検定を実施するためにはそれぞれを自由度で引いてあげる必要があります。データの総数は8ですので

総変動の自由度=8-1=7

になります。

そしてそれぞれの自由度ですが、マス目の色の数から1を引くとその自由度になります。つまり

肥料の自由度=2-1

土の自由度=2-1

次に交互作用の自由度ですが、マスの色の数は4なので1を引くと3ですが、その後に肥料の自由度と土の自由度も引いてあげる必要があります。よって

交互作用の自由度=(4-1)-1-1=1

です。そして誤差の自由度は、総変動の自由度からこれまで算出した自由度すべてを引きます。

誤差=7-(1+1+1)=4

そして導かれた変動を自由度で割ると分散が算出されます。

これらをすべて表にまとめると、このようになります。

ここからF検定を実施していきましょう

*** F検定で効果を確認

F検定は誤差に対して、有意差があるのか否かを確認するので、F値は各要因と
交互作用の分散を誤差の分散で除することで算出されます。

- [[https://sigma-eye.com/2018/09/13/f-test/][F検定？ばらつきの有意差を明確にしよう！【分散分析でも使います】]]

またF_{0.05}ですが、今回は奇しくもすべて自由度1,4の組み合わせであり、7.7になります。

これらの計算結果を表にすると以下のようになります。

[[
以上のようにF検定の結果、肥料と土にはそれぞれ有意差があるため効果があることが分かります。

そして交互作用は有意差が見られないので、交互作用は無いという事が分かります。

** エクセルで分散分析しよう

まず、*データタグ*の*データ分析*をクリックし、*分散分析：繰り返しの有る二元配置*を選択します。


*データ範囲*を指定します。*行数*は繰り返しの反復数を入力します(要は一条件当たりの*N数*です)。


結果が出力されます。注目すべきは下方に位置されている表のP-値です。


*標本*が土で、*列*が肥料に当たります(これが分かりづらい)。

当初の分析結果通り、P-値が有意水準α=0.05を下回っている項目は土と肥料です。

交互作用は認められません。

** まとめ

二元配置分散分析は使えるようになると、*交互作用の有無を見つけることが出来ます*。

交互作用が分かると、もしかしたらものすごい発見に繋がるかもしれません。

分析作業自体はエクセルで、極めて短時間で実施出来ますので、ぜひ使用してみて下さい。

