* 分散分析*
   [[https://www.ouj.ac.jp/mijika/tokei/xml/k3_06023.xml][分散分析*]]

   


実験により得られたデータ全体の平方和を，いくつかの要因効果に対応する平
方和と，その残りの誤差平方和に分解して検定や推定を行うこと．

** 解説　
一般にデータが与えられているとき，これらデータの変動は，個々のデータの
全体の平均値（）からの偏差の2乗和　　　　　　ここで，　　　　　として
求めることができる．これを（偏差）平方和とよぶ．　平方和 S は，見かけ
上　　　　　の個の成分の2乗和であるが，これら個の成分はすべて加えると0
になるという関係　　　　　がある．したがって，独立な成分の数は（）であ
る．このことから，平方和S は（）個の独立な成分の2乗和であると考えられ
る．このように，平方和が独立な成分の何個の2乗和になっているかを考えた
とき，独立な成分の個数を平方和の自由度とよぶ．また，平方和S をその自由
度（）で除したものを不偏分散または平均平方とよぶ．　平方和S をさらに意
味のある要因別に分解することを平方和の分解といい，これには，データがど
のような実験計画の下でとられているかを明確にする必要がある．この意味で，
後の解析の目的を考慮した計画的なデータの収集が極めて重要である．■1元
配置実験の分散分析　1因子A のみを取り上げて，その最適条件を求めるため
水準を選び，各水準で繰り返しの計回の実験を無作為に行うと，実験データは
表1のように得られる．

　このとき，データの構造模型は，
　　　　　
　ここで，：水準の効果，：平均0，分散の正規分布に従う誤差となる．
　全データの変動は，総平方和
　　　　　
　ここで，
　　　　　
によってはかられる．この平方和はさらに，Aの水準の違いによるばらつきと，実験誤差によるばらつきによるものに分解することができる.すなわち，
　　　
　　　
となる．このとき，平方和の自由度は，それぞれとなり，
　　　　　
の関係が成り立つ.
　これらの平方和を用いて，因子Aの効果があるかどうか，すなわち，
　　　　　
であるか否かの検定は次のようにできる．まず各平方和をその自由度で除して，不偏分散を求める.
　　　　　
　さらにAの不偏分散を誤差分散と比較するため，不偏分散比
　　　　　
を求める．もしA の効果が大きければ，は大きくなり，したがっても大きくなるからの値は大きくなる．したがってがある値以上になれば，A の効果があると判断できる．この判断基準の値は，有意水準（A の効果がないときに誤って効果があると判断する確率）を（通常がよく用いられる）とすれば，自由度，のＦ分布の上側点により与えられる.
　以上のことを表にまとめると，表2の分散分析表が得られる．

　なお平方和の計算は，定義式を用いるよりも次のように計算したほうがよい.
　　　　　
　　　　　
　　　　　
　　　　　


ここで，CT は平方和の計算にはつねにでてくる項で修正項とよばれる．
■2元配置実験の分散分析
　ここでは，ふたつの因子A （水準）B（水準）をとりあげ，各水準組み合わせの繰り返しの計回の実験を無作為化して行った実験データの分散分析について考える．この場合の実験データは，表3のようにで表すことができる．ただし，添字は因子の水準を，は因子の水準を，は繰り返しの番号を示す．また，記号は水準のデータの和，は水準のデータの平均値を表す．他の記号も同様に定義する．

　データの構造模型は，
　　　　　
と表されるが，はさらに
　　　　　

と書けるから，結局
　　　　　
となる．ただし，



である．交互作用はA，B どちらか一方の添字について和をとれば0になる．また誤差は平均0，分散の正規分布にしたがうものとする．この場合の仮説検定は，
（1）　A の主効果は存在するかどうか．
（2）　B の主効果は存在するかどうか．
（3）　A とB の交互作用A×B は存在するかどうか．
の３つになる．

　A の主効果，B の主効果，A×B の交互作用を検定するために，1因子要因実験の場合と同様に総平方和を
　　　　　
　　　　　
に分解することが必要になる．を計算するには，表4のAB 2元表を作成すると便利である．表4より，は，
　　　　　
と求められる．ここで，は修正項で，
　　　　　
である．はさらに，
　　　　　
に分解することができる．ここで，はA の水準間の効果の違いを表す平方和，はB の水準間の違いを表す平方和，は交互作用A×B の大きさを表す平方和である．，は，
　　　　　
　　　　　
と，そしては，
　　　　　
と求められる．なお，誤差平方和は，
　　　　　
から求められる．
　以上のことを分散分析表の形にまとめると，表5のようになる．これより，有意水準で
　　　　　
　　　　　
　　　　　
と判断する．最適条件を求めるには推定の考え方が必要．（宮村鐵夫）


＊この内容は，「統計・OR活用事典」（森村，牧野，真壁，杉山編）東京書籍（現在，絶版）をもとに執筆者が編集したものである．
関連用語： 　 要因効果* 　 実験計画法* 　 構造模型* 
